export const issueData = [
	{
		issue:"FY19 HP将持续进行产品升级，以下关于HP主推产品/工具优势描述错误的是：",
		answer:[
			{
				order:'A',
				texts:"Evera ICD的优势包括流线外形、智能电击、更长寿命",
				correct:false
			},
			{
				order:'B',
				texts:"美敦力Viva XT Quad CRTD、Viva XT CRTD和Viva CRTP具有AdaptivCRT功能，HRS上最新发布的carelink数据显示3年降低31%的相对死亡风险",
				correct:false
			},
			{
				order:'C',
				texts:"CRT植入跟台只需要备6250VIC（包含：6250VI-MB2和6250VI-EH）",
				correct:true
			},
			{
				order:'D',
				texts:"CRT植入跟台在配备6250VIC的基础上，需要加上6250VI-EHXL和6250VI-MPR，以适合特殊解剖结构",
				correct:false
			},
		]
	},
	{
		issue:"AFY19 HP将持续进行产品升级，以下关于Egida和Protecta的描述中错误的是：",
		answer:[
			{
				order:'A',
				texts:"Egida在目前的产品线中会最先退市",
				correct:false
			},
			{
				order:'B',
				texts:"我们希望使用Egida来替代Maximo II",
				correct:true
			},
			{
				order:'C',
				texts:"Protecta可以等价替换Maximo II",
				correct:false
			},
			{
				order:'D',
				texts:"我们希望减少使用Egida，多使用Evera/Viva/Brava",
				correct:false
			}
			
		]
	},
	{
		issue:"目前美敦力冷冻球囊消融导管全球应用超过多少例？",
		answer:[
			{
				order:'A',
				texts:"18万例",
				correct:false
			},
			{
				order:'B',
				texts:"28万例",
				correct:false
			},
			{
				order:'C',
				texts:"38万例",
				correct:true
			},
			{
				order:'D',
				texts:"48万例",
				correct:false
			},
		]
	},
	{
		issue:"以下关于FY19行冻中国项目说法错误的是",
		answer:[
			{
				order:'A',
				texts:"主要以主题讲座+手术演示的形式",
				correct:false
			},
			{
				order:'B',
				texts:"目标医院为冷冻占比低的大中心",
				correct:false
			},
			{
				order:'C',
				texts:"目标人数50-100人",
				correct:true
			},
			{
				order:'D',
				texts:"除本院医生，也可以邀请周边医院的医生参加",
				correct:false
			}
		]
	},
	{
		issue:"下列选项，哪些是FY19远程随访的生意模式？",
		answer:[
			{
				order:'A',
				texts:"下列选项，哪些是FY19远程随访的生意模式？",
				correct:false
			},
			{
				order:'B',
				texts:"招标绑定",
				correct:false
			},
			{
				order:'C',
				texts:"创新服务收费",
				correct:false
			},
			{
				order:'D',
				texts:"以上全部都是",
				correct:true
			}
		]
	},
	{
		issue:"关于开发医院项目LINQ Club项目描述正确的是：",
		answer:[
			{
				order:'A',
				texts:"疗法教育和术者经验分享的学术平台",
				correct:false
			},
			{
				order:'B',
				texts:"属于长程心电监测工作委员会规范化教育的一部分",
				correct:false
			},
			{
				order:'C',
				texts:"主要专注于晕厥管理",
				correct:false
			},
			{
				order:'D',
				texts:"以上都对",
				correct:true
			}
		]
	},
	{
		issue:"iPacing APP作为一款用于筛选患者，准确迅速判断患者是否需要植入起博器的APP，其诊断逻辑是基于以下哪个指南？",
		answer:[
			{
				order:'A',
				texts:"2008 ACC/AHA /HRS 心脏节律异常器械治疗指南",
				correct:false
			},
			{
				order:'B',
				texts:"2010中国植入性起搏器治疗建议",
				correct:false
			},
			{
				order:'C',
				texts:"2012 AHAF/ACC/HRS 心脏节律异常器械治疗指南 ",
				correct:false
			},
			{
				order:'D',
				texts:"2013 ESC 心脏起搏和再同步治疗指南",
				correct:true
			}
		]
	},
	{
		issue:"有关文献速递，以下描述错误的是：",
		answer:[
			{
				order:'A',
				texts:"文献速递每月发布一期",
				correct:false
			},
			{
				order:'B',
				texts:"每期文献速递包含最新发布的文献和经典文献解读",
				correct:false
			},
			{
				order:'C',
				texts:"内部发送的文献速递邮件未附上文献原文 ",
				correct:true
			},
			{
				order:'D',
				texts:"文献速递的发布方式包括邮件内部发送和心律界推送",
				correct:false
			}
		]
	},
	{
		issue:"印有美敦力标志的品牌提示物单个采购限额是多少人民币。",
		answer:[
			{
				order:'A',
				texts:"100",
				correct:false
			},
			{
				order:'B',
				texts:"150",
				correct:false
			},
			{
				order:'C',
				texts:"200 ",
				correct:true
			},
			{
				order:'D',
				texts:"250",
				correct:false
			}
		]
	},
	{
		issue:"2017年12月1日起公司所有合同都必须在哪个系统中生成、审核。",
		answer:[
			{
				order:'A',
				texts:"ieCATS",
				correct:false
			},
			{
				order:'B',
				texts:"iContract",
				correct:true
			},
			{
				order:'C',
				texts:"iOnesource",
				correct:false
			}
		]
	},
	{
		issue:"A3DR01为患者提供了从诊断、预防到干预全面的房颤管理方案，以下哪些性支持这个解决方案？",
		answer:[
			{
				order:'A',
				texts:"高达96.2%的准确诊断率",
				correct:false
			},
			{
				order:'B',
				texts:"MVP",
				correct:false
			},
			{
				order:'C',
				texts:"心房reactive ATP",
				correct:false
			},
			{
				order:'D',
				texts:"	MRI SureScan",
				correct:false
			},
			{
				order:'E',
				texts:"以上全部",
				correct:true
			}
		]
	},
		{
		issue:"以下哪个不是3830电极的特性",
		answer:[
			{
				order:'A',
				texts:"直径4.1 Fr",
				correct:false
			},
			{
				order:'B',
				texts:"绝缘层为聚氨酯",
				correct:false
			},
			{
				order:'C',
				texts:"兼容C315和C304鞘管",
				correct:false
			},
			{
				order:'D',
				texts:"电极螺旋头端1.8mm",
				correct:false
			},
			{
				order:'E',
				texts:"无法与A3DR01搭配使用",
				correct:true
			}
		]
	}
]

